(function(){
'use strict';
var state={project:null,projectPath:'',sourceUrl:'',preview:null,previewGeometry:null,previewError:'',lastBuiltPackage:''};
var applying=false,dirty=false,saveTimer=0,toastTimer=0,selectedVariant='small',previewReady=false,activeView='fp';
function byId(id){return document.getElementById(id)}
function post(value){if(window.chrome&&window.chrome.webview)window.chrome.webview.postMessage(value)}
function text(id,value){var el=byId(id);if(el)el.textContent=value==null?'':String(value)}
function shortPath(value){if(!value)return 'NOT SELECTED';var parts=String(value).replace(/\\/g,'/').split('/');return parts.length>4?'…/'+parts.slice(-4).join('/'):parts.join('/')}
function finite(value,fallback){var n=Number(value);return isFinite(n)?n:fallback}
function setDisabled(disabled){['saveProject','validateProject','buildProject'].forEach(function(id){byId(id).disabled=disabled||!state.project})}
function profileKey(view){return view==='tp'?'ThirdPersonTransform':'FirstPersonTransform'}
function activeTransform(p){return p&&p[profileKey(activeView)]||{}}
function readTransformInputs(target){target=target||{};target.PositionX=finite(byId('posX').value,0);target.PositionY=finite(byId('posY').value,0);target.PositionZ=finite(byId('posZ').value,0);target.RotationX=finite(byId('rotX').value,0);target.RotationY=finite(byId('rotY').value,0);target.RotationZ=finite(byId('rotZ').value,0);target.UniformScale=finite(byId('uniformScale').value,1);target.TranslationSnap=finite(byId('moveSnap').value,1);target.RotationSnap=finite(byId('angleSnap').value,5);target.ScaleSnap=finite(byId('scaleSnap').value,.05);return target}
function showTransform(t){t=t||{};applying=true;setNumber('posX',t.PositionX);setNumber('posY',t.PositionY);setNumber('posZ',t.PositionZ);setNumber('rotX',t.RotationX);setNumber('rotY',t.RotationY);setNumber('rotZ',t.RotationZ);setNumber('uniformScale',t.UniformScale||1);setNumber('moveSnap',t.TranslationSnap||1);setNumber('angleSnap',t.RotationSnap||5);setNumber('scaleSnap',t.ScaleSnap||.05);applying=false;text('transformProfile',(activeView==='tp'?'THIRD PERSON':'FIRST PERSON')+' · CM')}
function collectProject(){
 if(!state.project)return null;
 var p=JSON.parse(JSON.stringify(state.project));
 p.ProjectName=byId('projectName').value.trim()||'TreeSaplingHeldTool';
 p.SourceMesh.ModelName=byId('modelName').value.trim();
 p.SourceMesh.MaterialName=byId('materialName').value.trim();
 var key=profileKey(activeView);p[key]=readTransformInputs(p[key]||{});p.Transform=null;
 return p;
}
function setNumber(id,value){byId(id).value=Number(value||0).toFixed(id==='uniformScale'?3:2).replace(/\.?0+$/,'')||'0'}
function renderProject(){
 var p=state.project;byId('welcomePanel').classList.toggle('hidden',!!p);byId('projectControls').classList.toggle('hidden',!p);
 byId('projectLamp').parentElement.classList.toggle('ready',!!p);text('projectState',p?'PROJECT READY':'NO PROJECT');setDisabled(false);
 byId('revealBuild').disabled=!state.lastBuiltPackage;
 if(!p){text('previewTitle','WAITING FOR PROJECT');byId('previewEmpty').classList.remove('hidden');return}
 applying=true;
 byId('projectName').value=p.ProjectName||'';text('sourcePath',shortPath(p.SourceMesh&&p.SourceMesh.OriginalPath));text('gamePath',shortPath(p.GameRoot)||'NOT FOUND');text('integrationPath',shortPath(p.IntegrationSourcePath));text('outputPath',shortPath(p.Output&&p.Output.BaseDirectory));
 byId('modelName').value=p.SourceMesh&&p.SourceMesh.ModelName||'';byId('materialName').value=p.SourceMesh&&p.SourceMesh.MaterialName||'';
 showTransform(activeTransform(p));
 renderVariants(p.Variants||[]);text('previewTitle',(p.ProjectName||'TREE SAPLING TOOL').toUpperCase());applying=false;dirty=false;
 loadPreview();
}
function renderVariants(variants){var root=byId('variantSwitches');root.innerHTML='';variants.forEach(function(v){var b=document.createElement('button');b.type='button';b.className='variant'+(v.Key===selectedVariant?' active':'');b.style.setProperty('--variant','#'+v.Color);b.setAttribute('data-key',v.Key);b.innerHTML='<i></i><strong>'+escapeHtml(v.DisplayName||v.Key)+'</strong>';b.onclick=function(){selectedVariant=v.Key;renderVariants(variants);if(window.toolForgePreview)window.toolForgePreview.setVariant(v.Color)};root.appendChild(b)})}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function currentVariant(){if(!state.project)return null;var vars=state.project.Variants||[];for(var i=0;i<vars.length;i++)if(vars[i].Key===selectedVariant)return vars[i];return vars[0]||null}
function loadPreview(){if(!previewReady||!state.project||!window.toolForgePreview)return;var p=collectProject(),v=currentVariant(),mesh=state.project.SourceMesh||{};state.project=p;window.toolForgePreview.load({sourceUrl:state.sourceUrl,previewGeometry:state.previewGeometry,assets:state.preview,previewError:state.previewError,transform:activeTransform(p),upright:{RotationX:finite(mesh.SuggestedRotationX,0),RotationY:finite(mesh.SuggestedRotationY,0),RotationZ:finite(mesh.SuggestedRotationZ,0)},textureMode:mesh.TextureMode||'vanilla-leafplant',color:v?v.Color:'ffffff',view:activeView})}
function scheduleSave(){if(applying||!state.project)return;dirty=true;text('projectState','UNSAVED CHANGES');clearTimeout(saveTimer);saveTimer=setTimeout(function(){var p=collectProject();if(!p)return;state.project=p;post({type:'saveProject',silent:'true',projectJson:JSON.stringify(p)});dirty=false;text('projectState','PROJECT READY')},650)}
function syncPreviewFromInputs(){if(!window.toolForgePreview||!state.project)return;var p=collectProject();state.project=p;window.toolForgePreview.setTransform(activeTransform(p))}
function showToast(title,message,kind){var toast=byId('toast');toast.className='toast show '+(kind||'');toast.querySelector('strong').textContent=title||'';toast.querySelector('span').textContent=message||'';clearTimeout(toastTimer);toastTimer=setTimeout(function(){toast.className='toast'},5200)}
function renderReport(report){var drawer=byId('validationDrawer'),body=byId('validationBody');drawer.classList.add('open');var issues=report&&report.Issues||[];var errors=issues.filter(function(i){return String(i.Severity).toUpperCase()==='ERROR'}).length;var warnings=issues.length-errors;text('validationCount',errors?errors+' ERRORS':warnings?warnings+' WARNINGS':'READY');body.innerHTML='<div class="report-item"><b>FBX</b><span>'+escapeHtml(((report&&report.FbxFormat)||'').trim()+' '+(report&&report.FbxVersion||'—'))+'</span><span>'+Number(report&&report.VertexCount||0).toLocaleString()+' vertices · '+Number(report&&report.PolygonCount||0).toLocaleString()+' polygons</span></div>';
 if(!issues.length)body.innerHTML+='<div class="report-item"><b>PASS</b><span>ALL CHECKS</span><span>Source hash, mesh structure, game assets, UUIDs, and integration markers are valid.</span></div>';
 issues.forEach(function(i){var sev=String(i.Severity||'').toLowerCase();body.innerHTML+='<div class="report-item '+sev+'"><b>'+escapeHtml(i.Severity)+'</b><span>'+escapeHtml(i.Code)+'</span><span>'+escapeHtml(i.Message)+(i.Path?'<br><small>'+escapeHtml(shortPath(i.Path))+'</small>':'')+'</span></div>'})}
function buildResult(result){if(!result)return;if(result.Validation)renderReport(result.Validation);if(result.Success){state.lastBuiltPackage=result.PackagePath;byId('revealBuild').disabled=false;showToast('PACKAGE BUILT',result.PackagePath,'good')}else showToast('BUILD BLOCKED','Fix the validation errors before building.','bad')}
function bind(){
 window.addEventListener('error',function(e){var detail=e.error&&e.error.stack?e.error.stack:(e.message||'unknown JavaScript error');post({type:'previewStatus',loaded:false,error:'Preview script error: '+detail,rig:'OFFLINE',joint:'—'})});
 window.addEventListener('unhandledrejection',function(e){var reason=e.reason&&e.reason.message?e.reason.message:String(e.reason||'unknown promise rejection');post({type:'previewStatus',loaded:false,error:'Preview promise error: '+reason,rig:'OFFLINE',joint:'—'})});
 byId('newProject').onclick=byId('welcomeNew').onclick=function(){post({type:'newProject'})};byId('openProject').onclick=function(){post({type:'openProject'})};byId('saveProject').onclick=function(){var p=collectProject();if(p)post({type:'saveProject',projectJson:JSON.stringify(p)})};
 byId('validateProject').onclick=function(){var p=collectProject();if(p)post({type:'validate',projectJson:JSON.stringify(p)})};byId('buildProject').onclick=function(){var p=collectProject();if(p)post({type:'build',projectJson:JSON.stringify(p)})};byId('revealBuild').onclick=function(){post({type:'reveal'})};
 byId('pickGame').onclick=function(){post({type:'pickGame'})};byId('pickIntegration').onclick=function(){post({type:'pickIntegration'})};byId('pickOutput').onclick=function(){post({type:'pickOutput'})};
 document.querySelectorAll('[data-window]').forEach(function(b){b.onclick=function(){post({type:'window',action:b.getAttribute('data-window')})}});byId('titlebar').onmousedown=function(e){if(e.button===0&&!e.target.closest('button'))post({type:'window',action:'drag'})};
 ['projectName','modelName','materialName','posX','posY','posZ','rotX','rotY','rotZ','uniformScale','moveSnap','angleSnap','scaleSnap'].forEach(function(id){byId(id).addEventListener('input',function(){scheduleSave();if(/^(pos|rot|uniform|moveSnap|angleSnap|scaleSnap)/.test(id))syncPreviewFromInputs()})});
 document.querySelectorAll('[data-transform-mode]').forEach(function(b){b.onclick=function(){document.querySelectorAll('[data-transform-mode]').forEach(function(x){x.classList.remove('active')});b.classList.add('active');if(window.toolForgePreview)window.toolForgePreview.setTransformMode(b.getAttribute('data-transform-mode'))}});
 document.querySelectorAll('[data-view]').forEach(function(b){b.onclick=function(){if(b.getAttribute('data-view')===activeView)return;state.project=collectProject();activeView=b.getAttribute('data-view');document.querySelectorAll('[data-view]').forEach(function(x){x.classList.toggle('active',x.getAttribute('data-view')===activeView)});showTransform(activeTransform(state.project));scheduleSave();loadPreview()}});
 byId('copyFpToTp').onclick=function(){state.project=collectProject();state.project.ThirdPersonTransform=JSON.parse(JSON.stringify(state.project.FirstPersonTransform));if(activeView==='tp')showTransform(state.project.ThirdPersonTransform);scheduleSave();loadPreview();showToast('PROFILE COPIED','First-person alignment copied to third person.','good')};
 byId('copyTpToFp').onclick=function(){state.project=collectProject();state.project.FirstPersonTransform=JSON.parse(JSON.stringify(state.project.ThirdPersonTransform));if(activeView==='fp')showTransform(state.project.FirstPersonTransform);scheduleSave();loadPreview();showToast('PROFILE COPIED','Third-person alignment copied to first person.','good')};
 byId('undoTransform').onclick=function(){if(window.toolForgePreview)window.toolForgePreview.undo()};byId('redoTransform').onclick=function(){if(window.toolForgePreview)window.toolForgePreview.redo()};byId('resetTransform').onclick=function(){if(window.toolForgePreview)window.toolForgePreview.resetTransform()};byId('uprightPreset').onclick=function(){if(window.toolForgePreview)window.toolForgePreview.applyUprightPreset()};
 ['toggleGrid','toggleAxes','toggleBox','toggleWire','toggleClay','toggleScreen'].forEach(function(id){byId(id).onclick=function(){var on=this.classList.toggle('active');if(window.toolForgePreview)window.toolForgePreview.toggle(id.replace('toggle','').toLowerCase(),on)}});byId('focusModel').onclick=function(){if(window.toolForgePreview)window.toolForgePreview.focus()};
 byId('animationSelect').onchange=function(){if(window.toolForgePreview)window.toolForgePreview.setAnimation(this.value)};byId('playPause').onclick=function(){if(window.toolForgePreview)window.toolForgePreview.togglePlayback()};byId('restartAnimation').onclick=function(){if(window.toolForgePreview)window.toolForgePreview.restartAnimation()};byId('animationTimeline').oninput=function(){if(window.toolForgePreview)window.toolForgePreview.seek(Number(this.value))};
 byId('drawerToggle').onclick=function(){byId('validationDrawer').classList.toggle('open')};
 window.addEventListener('toolforge-preview-ready',function(){previewReady=true;loadPreview()});
 window.addEventListener('toolforge-transform',function(e){if(applying||!state.project)return;var t=e.detail;applying=true;setNumber('posX',t.PositionX);setNumber('posY',t.PositionY);setNumber('posZ',t.PositionZ);setNumber('rotX',t.RotationX);setNumber('rotY',t.RotationY);setNumber('rotZ',t.RotationZ);setNumber('uniformScale',t.UniformScale);applying=false;scheduleSave()});
 window.addEventListener('toolforge-preview-status',function(e){var d=e.detail||{};text('rigBadge','RIG: '+(d.rig||'OFFLINE'));text('jointBadge','JOINT: '+(d.joint||'—'));byId('viewportError').classList.toggle('hidden',!d.error);text('viewportError',d.error||'');byId('previewEmpty').classList.toggle('hidden',!!d.loaded);post({type:'previewStatus',loaded:!!d.loaded,error:d.error||'',rig:d.rig||'OFFLINE',joint:d.joint||'—'})});
 window.addEventListener('toolforge-animations',function(e){var d=e.detail||{},select=byId('animationSelect');select.innerHTML='';var none=document.createElement('option');none.value='none';none.textContent='NONE';select.appendChild(none);(d.animations||[]).forEach(function(a){var o=document.createElement('option');o.value=a.Name;o.textContent=a.Name.toUpperCase();select.appendChild(o)});select.disabled=!d.animations||!d.animations.length;if(d.current)select.value=d.current;var inactive=select.value==='none';byId('playPause').disabled=select.disabled||inactive;byId('restartAnimation').disabled=select.disabled||inactive;byId('animationTimeline').disabled=select.disabled||inactive;text('animationName',(d.current||'none').toUpperCase())});
 window.addEventListener('toolforge-animation-time',function(e){var d=e.detail||{},inactive=String(d.name||'none').toLowerCase()==='none';byId('animationTimeline').value=d.duration?d.time/d.duration:0;byId('playPause').disabled=inactive;byId('restartAnimation').disabled=inactive;byId('animationTimeline').disabled=inactive;text('animationTime',inactive?'NO CLIP':(d.time||0).toFixed(2)+' / '+(d.duration||0).toFixed(2));text('animationName',(d.name||'none').toUpperCase());byId('playPause').innerHTML=d.playing?'&#10074;&#10074;':'&#9654;'});
 window.addEventListener('toolforge-fps',function(e){text('fpsBadge',Math.round(e.detail||0)+' FPS')});
}
if(window.chrome&&window.chrome.webview)window.chrome.webview.addEventListener('message',function(e){var m=e.data||{};if(m.type==='state'){state.project=m.project||null;state.projectPath=m.projectPath||'';state.sourceUrl=m.sourceUrl||'';state.preview=m.preview||null;state.previewGeometry=m.previewGeometry||null;state.previewError=m.previewError||'';state.lastBuiltPackage=m.lastBuiltPackage||'';renderProject()}else if(m.type==='operation')showToast(m.title,m.message,m.ok?'good':'bad');else if(m.type==='validation')renderReport(m.report);else if(m.type==='buildResult')buildResult(m.result);else if(m.type==='busy'){var b=byId('busyReadout');b.classList.toggle('busy',!!m.busy);b.querySelector('em').textContent=m.busy?m.message:'READY';setDisabled(!!m.busy)}});
bind();post({type:'ready'});
})();
