using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;

namespace ScrapLab.ToolForge
{
    internal static class TreeSaplingToolGenerator
    {
        internal const string HeldRenderableFpGamePath =
            "$SURVIVAL_DATA/Character/Char_Tools/ScrapLab/TreeSaplings/TreeSaplingHeldFp.rend";
        internal const string HeldRenderableTpGamePath =
            "$SURVIVAL_DATA/Character/Char_Tools/ScrapLab/TreeSaplings/TreeSaplingHeldTp.rend";

        internal static string GenerateRenderable(ToolForgeProject project,
            string profile)
        {
            string suffix = String.Equals(profile, "fp",
                StringComparison.OrdinalIgnoreCase) ? "Fp" : "Tp";
            string textureStem = ResolveTextureStem(project);
            return "{\n" +
                "  \"lodList\" : [\n" +
                "    {\n" +
                "      \"maxViewDistance\" : 1000.0,\n" +
                "      \"mesh\" : \"$SURVIVAL_DATA/Character/Char_Tools/ScrapLab/TreeSaplings/TreeSaplingHeld" + suffix + ".dae\",\n" +
                "      \"subMeshMap\" : {\n" +
                "        \"" + JsonEscape(project.SourceMesh.MaterialName) + "\" : {\n" +
                "          \"material\" : \"DifAsgNorAlpha\",\n" +
                "          \"textureList\" : [\n" +
                "            \"$GAME_DATA/Objects/Textures/plants/" + textureStem + "_dif.tga\",\n" +
                "            \"$GAME_DATA/Objects/Textures/plants/" + textureStem + "_asg.tga\",\n" +
                "            \"$GAME_DATA/Objects/Textures/plants/" + textureStem + "_nor.tga\"\n" +
                "          ]\n" +
                "        }\n" +
                "      }\n" +
                "    }\n" +
                "  ]\n" +
                "}\n";
        }

        internal static string ResolveTextureStem(ToolForgeProject project)
        {
            string mode = project == null || project.SourceMesh == null
                ? String.Empty : project.SourceMesh.TextureMode;
            if (String.Equals(mode, "vanilla-poleplant",
                StringComparison.OrdinalIgnoreCase))
                return "obj_plants_poleplant";
            if (String.Equals(mode, "vanilla-leafplant",
                StringComparison.OrdinalIgnoreCase))
                return "obj_plants_leafplant";
            throw new InvalidDataException("Unsupported held-tool texture mode '" +
                mode + "'. Re-import the source FBX so Tool Forge can match its material atlas.");
        }

        internal static string GenerateVisualLua(ToolForgeProject project)
        {
            StringBuilder text = new StringBuilder();
            text.Append("-- Generated by ScrapLab Tool Forge. Do not edit this generated copy.\n");
            text.Append("-- ScrapLab invalidates the compiled Mesh cache whenever this held asset changes.\n");
            text.Append("ScrapLabTreeSaplingVisual = ScrapLabTreeSaplingVisual or {}\n\n");
            text.Append("local HeldRenderableTp = \"")
                .Append(HeldRenderableTpGamePath).Append("\"\n");
            text.Append("local HeldRenderableFp = \"")
                .Append(HeldRenderableFpGamePath).Append("\"\n");
            text.Append("local RenderablesTp = {\n")
                .Append("\t\"$SURVIVAL_DATA/Character/Char_Male/Animations/char_male_tp_bucket.rend\",\n")
                .Append("\t\"$SURVIVAL_DATA/Character/Char_bucket/char_bucket_tp_animlist.rend\",\n")
                .Append("\tHeldRenderableTp\n}\n");
            text.Append("local RenderablesFp = {\n")
                .Append("\t\"$SURVIVAL_DATA/Character/Char_Male/Animations/char_male_fp_bucket.rend\",\n")
                .Append("\t\"$SURVIVAL_DATA/Character/Char_bucket/char_bucket_fp_animlist.rend\",\n")
                .Append("\tHeldRenderableFp\n}\n\n");
            text.Append("ScrapLabTreeSaplingVisual.colors = {\n");
            foreach (ToolVariant variant in project.Variants)
                text.Append("\t").Append(variant.Key).Append(" = sm.color.new( 0x")
                    .Append(variant.Color.ToLowerInvariant()).Append("ff ),\n");
            text.Append("}\n\n");
            text.Append("sm.tool.preloadRenderables( { HeldRenderableTp, HeldRenderableFp } )\n")
                .Append("sm.tool.preloadRenderables( RenderablesTp )\n")
                .Append("sm.tool.preloadRenderables( RenderablesFp )\n\n");
            text.Append("function ScrapLabTreeSaplingVisual.apply( tool, color )\n")
                .Append("\ttool:setTpRenderables( RenderablesTp )\n")
                .Append("\ttool:setTpColor( color )\n")
                .Append("\tif tool:isLocal() then\n")
                .Append("\t\ttool:setFpRenderables( RenderablesFp )\n")
                .Append("\t\ttool:setFpColor( color )\n")
                .Append("\tend\n")
                .Append("end\n");
            return text.ToString();
        }

        internal static string GenerateIntegratedTool(string source,
            ToolForgeProject project)
        {
            const string generatedDofile =
                "dofile \"$SURVIVAL_DATA/Scripts/ScrapLab/Parts/TreeSaplings/TreeSaplingVisual.generated.lua\"";
            if (Count(source, generatedDofile) == 0)
            {
                const string anchor =
                    "dofile \"$SURVIVAL_DATA/Scripts/game/survival_items.lua\"";
                RequireCount(source, anchor, 1);
                source = source.Replace(anchor, anchor + "\n" + generatedDofile);
            }
            else RequireCount(source, generatedDofile, 1);

            string loadAnimations =
                "function TreeSaplingToolBase.cl_loadAnimations( self )\n" +
                "\tself.tpAnimations = createTpAnimations( self.tool, {\n" +
                "\t\tidle = { \"bucket_idle\", { looping = true } },\n" +
                "\t\tuse = { \"bucket_use_full\", { nextAnimation = \"idle\" } },\n" +
                "\t\tpickup = { \"bucket_pickup\", { nextAnimation = \"idle\" } },\n" +
                "\t\tputdown = { \"bucket_putdown\" }\n" +
                "\t} )\n" +
                "\tlocal movement = {\n" +
                "\t\tidle = \"bucket_idle\", runFwd = \"bucket_run\",\n" +
                "\t\trunBwd = \"bucket_runbwd\", sprint = \"bucket_sprint_idle\",\n" +
                "\t\tsprintLeft = \"bucket_sprint_left\", sprintRight = \"bucket_sprint_right\",\n" +
                "\t\tjump = \"bucket_jump\", jumpUp = \"bucket_jump_up\",\n" +
                "\t\tjumpDown = \"bucket_jump_down\", land = \"bucket_jump_land\",\n" +
                "\t\tlandFwd = \"bucket_jump_land_fwd\", landBwd = \"bucket_jump_land_bwd\",\n" +
                "\t\tlandLeft = \"bucket_jump_land_left\", landRight = \"bucket_jump_land_right\",\n" +
                "\t\tcrouchIdle = \"bucket_crouch_idle\", crouchFwd = \"bucket_crouch_run\",\n" +
                "\t\tcrouchBwd = \"bucket_crouch_runbwd\"\n" +
                "\t}\n" +
                "\tfor name, animation in pairs( movement ) do\n" +
                "\t\tself.tool:setMovementAnimation( name, animation )\n" +
                "\tend\n" +
                "\tif self.tool:isLocal() then\n" +
                "\t\tself.fpAnimations = createFpAnimations( self.tool, {\n" +
                "\t\t\tidle = { \"bucket_idle\", { looping = true } },\n" +
                "\t\t\tuse = { \"bucket_use_full\", { nextAnimation = \"idle\" } },\n" +
                "\t\t\tsprintInto = { \"bucket_sprint_into\", { nextAnimation = \"sprintIdle\", blendNext = 0.2 } },\n" +
                "\t\t\tsprintIdle = { \"bucket_sprint_idle\", { looping = true } },\n" +
                "\t\t\tsprintExit = { \"bucket_sprint_exit\", { nextAnimation = \"idle\", blendNext = 0 } },\n" +
                "\t\t\tjump = { \"bucket_jump\", { nextAnimation = \"idle\" } },\n" +
                "\t\t\tland = { \"bucket_jump_land\", { nextAnimation = \"idle\" } },\n" +
                "\t\t\tequip = { \"bucket_pickup\", { nextAnimation = \"idle\" } },\n" +
                "\t\t\tunequip = { \"bucket_putdown\" }\n" +
                "\t\t} )\n" +
                "\tend\n" +
                "\tsetTpAnimation( self.tpAnimations, \"idle\", 5.0 )\n" +
                "\tself.blendTime = 0.2\n" +
                "end\n";
            source = ReplaceFunctionBefore(source,
                "TreeSaplingToolBase.cl_loadAnimations",
                "TreeSaplingToolBase.cl_updateRenderables", loadAnimations);

            string updateRenderables =
                "function TreeSaplingToolBase.cl_updateRenderables( self )\n" +
                "\tScrapLabTreeSaplingVisual.apply( self.tool, self.config.color )\n" +
                "end\n";
            source = ReplaceFunctionBefore(source,
                "TreeSaplingToolBase.cl_updateRenderables",
                "TreeSaplingToolBase.client_onDestroy", updateRenderables);
            foreach (ToolVariant variant in project.Variants)
            {
                RequireCount(source, variant.ItemUuid, 1);
            }
            return source;
        }

        internal static string GenerateAssetsManifest(ToolForgeProject project)
        {
            var value = new
            {
                SchemaVersion = 1,
                Template = "tree-saplings",
                Definition = 2,
                Assets = new object[]
                {
                    new { Source = "TreeSaplingHeldFp.fbx", Target = "Survival/Character/Char_Tools/ScrapLab/TreeSaplings/TreeSaplingHeldFp.fbx", Kind = "binary" },
                    new { Source = "TreeSaplingHeldFp.dae", Target = "Survival/Character/Char_Tools/ScrapLab/TreeSaplings/TreeSaplingHeldFp.dae", Kind = "text" },
                    new { Source = "TreeSaplingHeldFp.rend", Target = "Survival/Character/Char_Tools/ScrapLab/TreeSaplings/TreeSaplingHeldFp.rend", Kind = "text" },
                    new { Source = "TreeSaplingHeldTp.fbx", Target = "Survival/Character/Char_Tools/ScrapLab/TreeSaplings/TreeSaplingHeldTp.fbx", Kind = "binary" },
                    new { Source = "TreeSaplingHeldTp.dae", Target = "Survival/Character/Char_Tools/ScrapLab/TreeSaplings/TreeSaplingHeldTp.dae", Kind = "text" },
                    new { Source = "TreeSaplingHeldTp.rend", Target = "Survival/Character/Char_Tools/ScrapLab/TreeSaplings/TreeSaplingHeldTp.rend", Kind = "text" },
                    new { Source = "TreeSaplingVisual.generated.lua", Target = "Survival/Scripts/ScrapLab/Parts/TreeSaplings/TreeSaplingVisual.generated.lua", Kind = "text" },
                    new { Source = "TreeSaplingTool.generated.lua", Target = "Survival/Scripts/ScrapLab/Parts/TreeSaplings/TreeSaplingTool.lua", Kind = "review-copy" }
                },
                Variants = project.Variants
            };
            return ToolForgeUtilities.SerializePretty(value) + "\n";
        }

        private static string ReplaceFunctionBefore(string source,
            string functionName, string nextFunctionName, string replacement)
        {
            string startMarker = "function " + functionName;
            string nextMarker = "function " + nextFunctionName;
            RequireCount(source, startMarker, 1);
            RequireCount(source, nextMarker, 1);
            int start = source.IndexOf(startMarker, StringComparison.Ordinal);
            int next = source.IndexOf(nextMarker, start + startMarker.Length,
                StringComparison.Ordinal);
            if (next <= start)
                throw new InvalidDataException("The protected Lua function order changed.");
            return source.Substring(0, start) + replacement + "\n" +
                source.Substring(next);
        }

        private static void RequireCount(string text, string value, int expected)
        {
            int count = Count(text, value);
            if (count != expected)
                throw new InvalidDataException("Protected text '" + value +
                    "' must appear " + expected + " time(s); found " + count + ".");
        }

        private static int Count(string text, string value)
        {
            int count = 0, index = 0;
            while ((index = text.IndexOf(value, index,
                StringComparison.Ordinal)) >= 0)
            {
                count++;
                index += value.Length;
            }
            return count;
        }

        private static string JsonEscape(string value)
        {
            return (value ?? String.Empty).Replace("\\", "\\\\")
                .Replace("\"", "\\\"");
        }
    }
}
