-- Generated by ScrapLab Tool Forge. Do not edit this generated copy.
-- ScrapLab invalidates the compiled Mesh cache whenever this held asset changes.
ScrapLabTreeSaplingVisual = ScrapLabTreeSaplingVisual or {}

local HeldRenderableTp = "$SURVIVAL_DATA/Character/Char_Tools/ScrapLab/TreeSaplings/TreeSaplingHeldTp.rend"
local HeldRenderableFp = "$SURVIVAL_DATA/Character/Char_Tools/ScrapLab/TreeSaplings/TreeSaplingHeldFp.rend"
local RenderablesTp = {
	"$SURVIVAL_DATA/Character/Char_Male/Animations/char_male_tp_bucket.rend",
	"$SURVIVAL_DATA/Character/Char_bucket/char_bucket_tp_animlist.rend",
	HeldRenderableTp
}
local RenderablesFp = {
	"$SURVIVAL_DATA/Character/Char_Male/Animations/char_male_fp_bucket.rend",
	"$SURVIVAL_DATA/Character/Char_bucket/char_bucket_fp_animlist.rend",
	HeldRenderableFp
}

ScrapLabTreeSaplingVisual.colors = {
	small = sm.color.new( 0x7eed56ff ),
	medium = sm.color.new( 0xe2db13ff ),
	large = sm.color.new( 0xdf7f00ff ),
}

sm.tool.preloadRenderables( { HeldRenderableTp, HeldRenderableFp } )
sm.tool.preloadRenderables( RenderablesTp )
sm.tool.preloadRenderables( RenderablesFp )

function ScrapLabTreeSaplingVisual.apply( tool, color )
	tool:setTpRenderables( RenderablesTp )
	tool:setTpColor( color )
	if tool:isLocal() then
		tool:setFpRenderables( RenderablesFp )
		tool:setFpColor( color )
	end
end
